# Copyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>

# Project:    Nord Atom Syntax
# Repository: https://github.com/arcticicestudio/nord-atom-syntax
# License:    MIT
# References:
#   https://docs.travis-ci.com
#   https://github.com/atom/ci

language: generic
dist: trusty
sudo: false
node_js:
  - "6.9.5"
env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"
    - LINUX_NVM_NODE_VERSION=6.9.5
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - build-essential
      - git
      - libgnome-keyring-dev
      - fakeroot
notifications:
  email:
    on_success: never
    on_failure: change
before_install:
  - rm -rf ./node_modules
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install $LINUX_NVM_NODE_VERSION;
      nvm use $LINUX_NVM_NODE_VERSION;
    fi
before_script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - npm install -g gulp-cli
  - npm install gulp
  - npm install
  - gulp --harmony lint
  - nvm deactivate
script:
  - ./build-package.sh
